
_target_: src.models.baselines.corrector_gan.lit_module.GANGenerator

generator:
  _target_: src.models.baselines.corrector_gan.models.CorrectorGen2
  _partial_: true

noise_shape: [6, 1, 16, 16]
input_channels: 8
zero_noise: true

# additional params
use_gradient_clipping: false
automatic_optimization: true
#corrector_ckpt: ${local.model_root_dir}/WassDiff-LiT/2024-10-07_14-08-01/checkpoints/epoch_049_step_077.ckpt

model_config:
  data:
    image_size: ${data.data_config.image_size}
    condition_mode: ${data.data_config.condition_mode}
    num_channels: ${data.data_config.num_channels}
    num_context_chs: ${data.data_config.num_context_chs}
    condition_size: ${data.data_config.condition_size}
    centered: ${data.data_config.centered}
    precip_rescale_c: ${data.data_config.precip_rescale_c}
  sampling:
    sampling_batch_size: 12