_target_: src.models.precip_downscale.wassdiff.WassDiffLitModule

compile: false
num_samples: 1 # for inference, aka ensemble size

# debugging flags
display_sampling_pbar: false  # display 'sampling N steps' progress bar
bypass_sampling: false  # during inference; training logging is not affected

optimizer_config:
  optim:
    weight_decay: 0
    optimizer: 'Adam'
    lr: 2e-4
    beta1: 0.9
    betas: [0.9, 0.999]
    eps: 1e-8
    warmup: 5000
    grad_clip: 1.0

#scheduler:

model_config:
  model:
    name: 'ncsnpp_cond'
    sigma_min: 0.01
    sigma_max: 50
    num_scales: 1000
    beta_min: 0.1
    beta_max: 20.0
    dropout: 0.1
    nonlinearity: 'swish'
    nf: 128
    ch_mult: [ 1, 2, 2, 2 ]
    num_res_blocks: 4
    attn_resolutions: [ 16 ]
    resamp_with_conv: true
    conditional: true  # likely for time condition, has nothing to do with conditional generation
    fir: true
    fir_kernel: [ 1, 3, 3, 1 ]
    skip_rescale: true
    resblock_type: 'biggan'
    progressive: 'none'
    progressive_input: 'residual'
    progressive_combine: 'sum'
    attention_type: 'ddpm'
    init_scale: 0.0
    embedding_type: 'positional'
    conv_size: 3
    ema_rate: 0.999
    scale_by_sigma: True
    # following is related to conditional sampling
    drop_prob: 0.1 # TODO: CIFAR used 0.2. Verify later
    w_guide: 0
    null_token: -1
  data:
    image_size: ${data.data_config.image_size}
    condition_mode: ${data.data_config.condition_mode}
    num_channels: ${data.data_config.num_channels}
    num_context_chs: ${data.data_config.num_context_chs}
    condition_size: ${data.data_config.condition_size}
    centered: ${data.data_config.centered}
    precip_rescale_c: ${data.data_config.precip_rescale_c}
  training:
    batch_size: null # TODO: remove this
    n_iters: 500000
    snapshot_sampling: false    # produce samples at each snapshot. Deprecated.
    likelihood_weighting: false
    continuous: false
    reduce_mean: true
    sde: 'vesde'
    task: 'super_resolution' # 'super_resolution' ONLY
    use_emd: true # earth mover's distance
    emd_weight: 0.2 # weight for EMD loss
    compute_rescaled_emd: false
  sampling:
    n_steps_each: 1
    noise_removal: true
    probability_flow: false
    snr: 0.16
    method: 'pc'
    predictor: 'reverse_diffusion'
    corrector: 'langevin'
    sampling_batch_size: 4

