#configs for tiled_diffusion
defaults:
  - wassdiff
  - _self_
_target_: src.models.precip_downscale.wassdiff_tiled.WassDiffTiledLitModule

tiled_diffusion: True

tiled_config:
  patch_size: 256
  stride: 192
  sf: 1
  batch_size: 6
  model_size: 512