# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
#data_dir: ${paths.root_dir}/data/
data_dir: ${local.data_dir}

# path to logging directory
#log_dir: /home/yl241/models/WassDiff-LiT
log_dir: ${local.log_dir}

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

dataset_path:
  base_path: ${paths.data_dir}
  mrms: '${paths.dataset_path.base_path}/nexrad'
  era5: '${paths.dataset_path.base_path}/ERA5'
  interpolated_era5: '${paths.dataset_path.base_path}/ERA5_INTERP'
  interpolated_cpc: '${paths.dataset_path.base_path}/CPC_INTERP/precip'
  interpolated_cpc_gauge: '${paths.dataset_path.base_path}/CPC_INTERP/gauge_density'
  cpc: '${paths.dataset_path.base_path}/CPC'
  mrms_daily: '${paths.dataset_path.base_path}/mrms_daily_12z_ending/' # precomputed daily aggregates
  cpc_gauge: '${paths.dataset_path.base_path}/CPC/GAUGE_CONUS_RT'
era5_filenames:
  surf_temp: "single_level/2m_temperature_{}.nc"
  elevation: "single_level/elevation.nc"
  vflux_e: "single_level/vertical_integral_of_eastward_water_vapour_flux_{}.nc"
  vflux_n: "single_level/vertical_integral_of_northward_water_vapour_flux_{}.nc"
  wind_u: "pressure_level/u_component_of_wind_500_{}.nc"
  wind_v: "pressure_level/v_component_of_wind_500_{}.nc"
cpc_filenames: 'precip.{}.nc'
interpolated_era5_filenames: 'era5_interp_merged_{}.nc'

