defaults:
  - model_checkpoint
#  - early_stopping
  - model_summary
  - rich_progress_bar
  - log_precip_data
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 20 # save k best models (determined by above metric)
  every_n_train_steps: 5000

#early_stopping:
#  monitor: "val/loss"
#  patience: 100
#  mode: "min"


model_summary:
  max_depth: -1
  summarize_kwargs:
    save_dir: ${paths.output_dir}  # assuming save_dir is stored under the wandb key in your config
