log_precip_data:
  _target_: src.utils.callbacks.precip_wandb_logger.PrecipDataLogger
  train_log_img_freq: 1000
  train_log_score_freq: 10000
  train_log_param_freq: 10000
  show_samples_at_start: false
  show_unconditional_samples: false