save_xarray_results:
  _target_: src.utils.callbacks.save_xarray_results.SaveXarrayResults
  save_dir: ${paths.output_dir}
  csi_threshold: ${metrics.csi_threshold}
  heavy_rain_threshold: ${metrics.heavy_rain_threshold}
  peak_mesoscale_threshold: ${metrics.peak_mesoscale_threshold}