# @package _global_

defaults:
  - data: cpc_mrms_data # choose datamodule with `test_dataloader()` for evaluation
  - model: wassdiff
  - metrics: default
#  - callbacks: specified_eval
#  - callbacks: eval_on_dataset
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - optional local: default
  - optional experiment: null
  - _self_

task_name: "eval"
tags: ["dev"]
ckpt_path: null
name: null

#### passing checkpoint path is necessary for evaluation

# WassDiff
model:
  num_samples: 1
  compile: true  # for speed up
  display_sampling_pbar: false  # debug
  pytorch_ckpt_path: ${local.model_root_dir}/NCSNPP/wandb/run-20240503_110757-gvq9r51l/checkpoints/checkpoint_21.pth


