# @package _global_

defaults:
  - data: cpc_mrms_data # choose datamodule with `test_dataloader()` for evaluation
  - model: wassdiff
  - metrics: default
  - callbacks: specified_eval
#  - callbacks: eval_on_dataset
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
   # optional local config for machine/user specific settings
   # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default
  - _self_

task_name: "eval"

tags: ["dev"]


# passing checkpoint path is necessary for evaluation
#ckpt_path: ${local.model_root_dir}/WassDiff-LiT/2024-09-05_20-56-22/checkpoints/epoch_740.ckpt
#ckpt_path:${local.model_root_dir}/WassDiff-LiT/2024-09-11_12-07-58/checkpoints/epoch_679.ckpt
#ckpt_path: ${local.model_root_dir}/WassDiff-LiT/2024-09-11_12-07-58/checkpoints/epoch_740.ckpt
#ckpt_path: ${local.model_root_dir}/WassDiff-LiT/2024-09-15_23-56-41/checkpoints/epoch_802.ckpt
ckpt_path: null

model:
  num_samples: 1
  compile: false
  display_sampling_pbar: true  # debug
  pytorch_ckpt_path: ${local.model_root_dir}/NCSNPP/wandb/run-20240503_110757-gvq9r51l/checkpoints/checkpoint_21.pth


#### SPECIFY EVAL MODE ####
name: debug_predefined_events_cold
event_name: cold_front
data:
  dataloader_mode: specify_eval
  batch_size: 1  # DO NOT MODIFY
  data_config:
    image_size: 256 # 512
  specify_eval_targets: ${data.known_eval_targets.${event_name}}
#  specify_eval_targets:
#    - date: '20150618'
#      lon: 265
#      lat: 36
paths:
  output_dir: ${local.specified_eval_root_dir}/${name}
  log_dir: ${paths.output_dir}


#### EVAL SET ########
#name: WassDiff_LiT_trained_120k_steps
#data:
#  dataloader_mode: eval_set_deterministic
#  use_test_samples_from: ${paths.data_dir}/rainfall_eval/50_eval_samples_2
#  stop_at_batch: 26
#  data_config:
#    image_size: 512
#
#paths:
#  output_dir:  ${local.eval_set_root_dir}/${name}
#  log_dir: ${paths.output_dir}


